### ISSUE TITLE
Incompatibility with babel 7

### ISSUE THREAD

**Issue by rubeniskov** [stackgl/babel-plugin-glslify#12]
In babel 7 the property  `state.file.log` is undefined and raises the following error

```textplain
{ TypeError: .../src/WidgetWorkspace3DViewer.js: Cannot read property 'filename' of undefined
    at PluginPass.CallExpression (.../node_modules/babel-plugin-glslify/glslify-babel.js:183:39)
    at newFn (.../node_modules/@babel/traverse/lib/visitors.js:175:21)
    at NodePath._call (.../node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (.../node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (.../node_modules/@babel/traverse/lib/path/context.js:92:31)
    at TraversalContext.visitQueue (.../node_modules/@babel/traverse/lib/context.js:116:16)
    at TraversalContext.visitMultiple (.../node_modules/@babel/traverse/lib/context.js:83:17)
    at TraversalContext.visit (.../node_modules/@babel/traverse/lib/context.js:142:19)
    at Function.traverse.node (.../node_modules/@babel/traverse/lib/index.js:82:17)
    at NodePath.visit (.../node_modules/@babel/traverse/lib/path/context.js:99:18) code: 'BABEL_TRANSFORM_ERROR' }
```

from this lines:
https://github.com/glslify/babel-plugin-glslify/blob/a9b799fab39007f5df5e7b7841118e70ddf46612/glslify-babel.js#L159
https://github.com/glslify/babel-plugin-glslify/blob/a9b799fab39007f5df5e7b7841118e70ddf46612/glslify-babel.js#L183

some references:
https://github.com/babel/babel/issues/7715
https://stackoverflow.com/questions/35857271/get-current-filename-in-babel-plugin

I will post a PR to fixed

Kind regards

**Comment by rubeniskov** [comment]
any update?

**Comment by marcofugaro** [comment]
Is this plugin dead?

**Comment by rubeniskov** [comment]
> Is this plugin dead?

it seems yes

**Comment by marcofugaro** [comment]
Switched to [babel-plugin-glsl](https://github.com/onnovisser/babel-plugin-glsl).

It has [this feature](https://github.com/onnovisser/babel-plugin-glsl#imported-function-names) which is actually very useful.

**Comment by glafarge** [comment]
@rubeniskov Thank's for the fix. 
Before the PR is accepted, you can [patch-package](https://www.npmjs.com/package/patch-package) with [those changes](https://github.com/glslify/babel-plugin-glslify/pull/13/files). Solved the issue for me.
