### ISSUE TITLE
Issue with Node 8.0.0

### ISSUE THREAD

**Issue by ataber** [stackgl/babel-plugin-glslify#8]
I'm seeing the following issue with this package when I try to build with node 8.0.0:
```
Module build failed: TypeError: /Users/andrewtaber/projects/intact-web/app/assets/javascripts/reactComponents/analysis/shaders.js: Unknown encoding: 0
    at stringSlice (buffer.js:557:9)
    at Uint8Array.Buffer.toString (buffer.js:593:10)
    at module.exports (/Users/andrewtaber/projects/intact-web/node_modules/babel-plugin-glslify/lib/glslify-sync-hack.js:28:64)
    at PluginPass.TaggedTemplateExpression (/Users/andrewtaber/projects/intact-web/node_modules/babel-plugin-glslify/glslify-babel.js:170:22)
    at newFn (/Users/andrewtaber/projects/intact-web/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/andrewtaber/projects/intact-web/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/andrewtaber/projects/intact-web/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/andrewtaber/projects/intact-web/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/andrewtaber/projects/intact-web/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/andrewtaber/projects/intact-web/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/andrewtaber/projects/intact-web/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/andrewtaber/projects/intact-web/node_modules/babel-traverse/lib/index.js:114:17)
 @ ./app/assets/javascripts/reactComponents/analysis/Canvas.js 15:15-35
```
[Here](https://github.com/nodejs/node/blob/bffc6a1bf844f8071daa629decb82eee4473de1a/lib/buffer.js#L516) is the relevant function in the node src (called from [here](https://github.com/nodejs/node/blob/master/lib/buffer.js#L594)).

It seems that [this line](https://github.com/stackgl/babel-plugin-glslify/blob/master/lib/glslify-sync-hack.js#L31) is responsible for the propagating `0` as the `encoding` variable...did the API to `buffer.toString()` change in 8.0.0?

**Comment by kevzettler** [comment]
Seeing this as well, removing the `0` fixes it

```
 Unknown encoding: 0
    at stringSlice (buffer.js:593:9)
    at Uint8Array.Buffer.toString (buffer.js:629:10)
    at module.exports (/Users/kev/code/robotbones/engines/stackgl/regl-budo/node_modules/babel-plugin-glslify/lib/glslify-sync-hack.js:33:64)
```

**Comment by milcktoast** [comment]
Still an issue in node `v8.5.0`.
